### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by mrcasual** [InterNations/antwort#28]
Hi,

Overall a solid attempt. There are a few (mostly common) rendering issues in some web and desktop clients. 

[Two-column layout]( https://www.emailonacid.com/beta/acidtest/display/summary/R6JBj42jvui4g0WIZipO1JCFSncjYeXcHsnQXX5tkwM3F/shared). Issue: spacing between ```<li>``` elements in Outlook (mobile and web) and Yahoo (Chrome/Mac). 

[Three-column layout] (https://www.emailonacid.com/beta/acidtest/display/summary/WmnZsge61jPvGQCw8zYQPiPrMpZ6PhrtflSWMbu1wRKrb/shared). Issue: spacing between images and ```<div class="subtitle">``` elements in Outlook (web).

Cheers.

**Comment by jng5** [comment]
You should never use `<li>` in an email. I just used it in the code walkthrough part that is not meant to be part of production code.

Yes, the `<div class="subtitle">` doesn't work because I use `margin` on the `<div>`.  Again, I just wanted to illustrate what a headline could look like.

I really meant for Antwort to be **layouts** but maybe some people prefer templates or patterns?

**Comment by mrcasual** [comment]
Is there a good reason against using ```<li```> elements? When done properly, there should be no rendering issues. Take a look at the following 3-column layout that passes all Litmus/EOA tests:

![three column layout](http://i.imgur.com/BsvTgDu.png)

**Comment by jng5** [comment]
There's huge discrepancies in terms of how bullets are rendered across clients. Best practice is to use tables.

If you're looking for patterns, you should also check this out: http://responsiveemailpatterns.com/
